[[plugins]]
# An extensible & universal comment vim-plugin that also handles embedded filetypes http://www.vim.org/scripts/script.php…
repo = 'tomtom/tcomment_vim'

[[plugins]]
# surround.vim: quoting/parenthesizing made simple http://www.vim.org/scripts/script.php…
repo = 'tpope/vim-surround'

[[plugins]]
# Smart line joint vim plugin.
repo = 'osyo-manga/vim-jplus'
lazy = 1
on_map = {n = '<Plug>'}
hook_add = '''
  nmap J <Plug>(jplus)
  vmap J <Plug>(jplus)
'''

# Text Object {{{
[[plugins]]
# Vim plugin: Create your own text objects http://www.vim.org/scripts/script.php…
repo = 'kana/vim-textobj-user'

[[plugins]]
# Text objects for Python.
repo = 'bps/vim-textobj-python'
on_ft = ['python']
#}}}
