# Vim Extension {{{
[[plugins]]
# A vim plugin to accelerate up-down moving! http://rhysd.hatenablog.com/
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
# Lightweight filer for Vim
repo = 'cocopon/vaffle.vim'
on_cmd = 'Vaffle'
hook_add = "call Source('rc/plugins/vaffle.rc.vim')"

[[plugins]]
# æŠ˜ã‚Šç•³ã¿é–¢æ•°ã¨ã€ç¾åœ¨éšå±¤ã‚’è¡¨ç¤ºã™ã‚‹æ©Ÿæ§‹ã‚’æä¾› http://d.hatena.ne.jp/leafcage/201112â€¦
repo = 'LeafCage/foldCC'
on_ft = 'vim'

[[plugins]]
# ğŸ““ Display vim version numbers in docs
repo = 'tweekmonster/helpful.vim'
on_cmd = 'HelpfulVersion'

[[plugins]]
# Vim plugin: Create your own text objects http://www.vim.org/scripts/script.phpâ€¦
repo = 'kana/vim-textobj-user'
#}}}

# [[plugins]]
# # CMake functionality within Vim. https://jalcine.github.io/cmake.vim
# repo = 'jalcine/cmake.vim'
# if = "executable('cmake')"
# on_ft = ['cmake']

# Git {{{
[[plugins]]
# Asynchronously control git repositories in Neovim/Vim 8 http://www.vim.org/scripts/script.phpâ€¦
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'
if = "g:is_nvim || g:is_vim8"

[[plugins]]
# A git wrapper focus on simplity and usability
repo = 'chemzqm/vim-easygit'
hook_add = '''
  let g:easygit_enable_command = 1
'''
# }}}

[[plugins]]
# Vim script for text filtering and alignment
repo = 'majutsushi/tagbar'
if = "executable('ctags')"
on_cmd = 'TagbarToggle'
hook_add = "call Source('rc/plugins/tagbar.rc.vim')"

[[plugins]]
# Ctags generator for Vim http://www.vim.org/scripts/script.phpâ€¦
repo = 'szw/vim-tags'
if = "executable('ctags')"
on_cmd = 'TagsGenerate'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
#Realtime preview by Vim. (Markdown, reStructuredText, textile)
repo = 'kannokanno/previm'
depends = 'open-browser.vim'
on_cmd = 'PrevimOpen'
